version: '3.7'
services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: foodcourt
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: foodcourt1

volumes:
  mysql_data:
